# config/_default/config.toml

colorScheme = "Terminal"

baseURL = "https://KevinQhv.com/"
languageCode = "en-us"
title = 'My website KevinQhv'
theme = 'blowfish'

[author]
name = "Kévin QUÉNÉHERVÉ"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { twitter = "https://twitter.com/username" }
]


topic = "my-first-post"



[[main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 30

[[main]]
  identifier = "github2"
  pre = "github"
  url = "https://github.com/nunocoracao/blowfish"
  weight = 40

[[footer]]
  name = "Privacy"
  url = "https://external-link"
